### ISSUE TITLE
Handle RuntimeWarning: divide by zero encountered in divide

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#132] opened 2015-06-17 15:15 UTC
Another warning I see often from the white dwarf run is this:
gPhoton/source/curvetools.py:323: RuntimeWarning: divide by zero encountered in divide
  lcurve['cps'] = lcurve['sources']/lcurve['exptime']
gPhoton/source/curvetools.py:325: RuntimeWarning: divide by zero encountered in divide
  lcurve['bg']['simple'])/lcurve['exptime']
gPhoton/source/curvetools.py:327: RuntimeWarning: divide by zero encountered in divide
  lcurve['bg']['cheese'])/lcurve['exptime']

If lcurve['exptime'] is zero we should catch that and use an appropriate fail value (inf, nan, zero, something).

Here's an example query that produced these errors:
gAperture.py -b NUV -r 3.4074 -d 0.3247 -s 30 --addhdr --gap 1000 -a 0.00166 -i 0.00222 -o 0.00333

**Comment by cmillion** [comment] 2015-06-19 19:51
I was not able to reproduce.

python ./gAperture.py -b NUV -r 3.4074 -d 0.3247 -s 30 --addhdr --gap 1000 -a 0.00166 -i 0.00222 -o 0.00333
[]
AB Magnitudes:               
[]

**Comment by cmillion** [comment] 2015-07-07 01:56
Note: Reproduce by changing numpy.seterr() to "warn."

**Comment by cmillion** [comment] 2015-07-07 03:20
Reproduced with the following commands.

    import numpy as np
    np.seterr(all='warn')
    band = 'NUV'
    skypos = [3.4074,0.3247]
    stepsz = 30
    maxgap = 1000
    radius = 0.00166
    annulus = [0.00222,0.00333]
    import gPhoton.curvetools
    blah = gPhoton.curvetools.getcurve(band,skypos[0],skypos[1],radius,annulus=annulus,stepsz=stepsz,maxgap=maxgap)

gPhoton/curvetools.py:320: RuntimeWarning: divide by zero encountered in divide
  lcurve['cps'] = lcurve['sources']/lcurve['exptime']
gPhoton/curvetools.py:322: RuntimeWarning: divide by zero encountered in divide
  lcurve['bg']['simple'])/lcurve['exptime']
gPhoton/curvetools.py:324: RuntimeWarning: divide by zero encountered in divide
  lcurve['bg']['cheese'])/lcurve['exptime']

**Comment by cmillion** [comment] 2015-07-07 03:26
Can't gloss over this one. Something is going wrong with the observational accounting. There are situations arising in which the calculated exposure time is zero but small numbers of photons are being detected. Investigating further.
    ix = np.where(blah['exptime']==0)
    blah['sources'][ix]
array([ 1.19835109,  1.1877564 ,  1.16063694,  1.16230087,  1.2260045 ,
        1.19300395,  1.18287548,  1.15736584,  1.16473327,  1.18962751,
        1.22344691,  1.22881337,  1.23399591,  1.19617641,  1.20592725,
        1.20879422,  1.18814621,  1.20167841,  1.19263067,  1.18445761,
        1.19679822,  1.19251302,  1.19739744,  1.22254358,  1.21500469,
        1.23795534])

**Comment by cmillion** [comment] 2015-07-14 20:10
After v1.25.0 -- which included a fix to the shutter correction -- this manifested as an outright error caused by passing time ranges of _zero_ length (i.e. t0==t1). This was happening because, for reasons that I don't remember, I was setting the bin boundaries on t[01]_data instead of t[01]. It probably had something to do with an idea about handling detector-edge cases. But for low count sources and shorter time bins, it was then really common to get only one event, leading to the error in question. This is fixed in v1.25.5.

**Closed by cmillion** 2015-07-14 20:10 UTC
Labels: bug
